/*!
    Module containing analogous Structs to IGDB endpoint responses.
*/
#[cfg(feature = "age_rating_content_description")]
pub mod age_rating_content_description;
#[cfg(feature = "age_rating")]
pub mod age_rating;
#[cfg(feature = "alternative_name")]
pub mod alternative_name;
#[cfg(feature = "artwork")]
pub mod artwork;
#[cfg(feature = "character_mug_shot")]
pub mod character_mug_shot;
#[cfg(feature = "collection")]
pub mod collection;
#[cfg(feature = "company_logo")]
pub mod company_logo;
#[cfg(feature = "company_website")]
pub mod company_website;
#[cfg(feature = "company")]
pub mod company;
#[cfg(feature = "cover")]
pub mod cover;
#[cfg(feature = "external_game")]
pub mod external_game;
#[cfg(feature = "franchise")]
pub mod franchise;
#[cfg(feature = "game_engine_logo")]
pub mod game_engine_logo;
#[cfg(feature = "game")]
pub mod game;
#[cfg(feature = "character")]
pub mod character;
#[cfg(feature = "genre")]
pub mod genre;
#[cfg(feature = "platform")]
pub mod platform;
#[cfg(feature = "theme")]
pub mod theme;
#[cfg(feature = "search")]
pub mod search;